apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginx-svc-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # 온프레미스: Cilium LB-IPAM이 172.16.200.0/24 대역에서 IP 할당
