apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP         # 기본값 (생략 가능)
  selector:
    app: nginx-svc-demo   # 이 라벨을 가진 Pod에 트래픽 전달
  ports:
    - protocol: TCP
      port: 80            # Service 포트
      targetPort: 80      # Pod의 컨테이너 포트
