apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    environment: training
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
